CREATE TABLE [dbo].[VehicleData] (
    [Id]                                  INT             IDENTITY (1, 1) NOT NULL,
    [TipoFichero]                         INT             NULL,
    [NombreFichero]                       NVARCHAR (250)  NULL,
    [FecMatricula]                        DATETIME        NULL,
    [CodClaseMat]                         INT             NULL,
    [FecTramitacion]                      DATETIME        NULL,
    [MarcaItv]                            NVARCHAR (30)   NULL,
    [ModeloItv]                           NVARCHAR (22)   NULL,
    [CodProcedenciaItv]                   NVARCHAR (1)    NULL,
    [BastidorItv]                         NVARCHAR (21)   NULL,
    [CodTipo]                             NVARCHAR (2)    NULL,
    [CodPropulsionItv]                    NVARCHAR (1)    NULL,
    [CilindradaItv]                       DECIMAL (18, 2) NULL,
    [PotenciaItv]                         DECIMAL (18, 2) NULL,
    [Tara]                                DECIMAL (18, 2) NULL,
    [PesoMax]                             DECIMAL (18, 2) NULL,
    [NumPlazasItv]                        INT             NULL,
    [IndPrecinto]                         NVARCHAR (2)    NULL,
    [IndEmbargo]                          NVARCHAR (2)    NULL,
    [NumTransmisiones]                    INT             NULL,
    [NumTitulares]                        INT             NULL,
    [LocalidadVehiculo]                   NVARCHAR (24)   NULL,
    [CodProvinciaVeh]                     NVARCHAR (2)    NULL,
    [CodProvinciaMat]                     NVARCHAR (2)    NULL,
    [ClaveTramite]                        NVARCHAR (1)    NULL,
    [FecTramite]                          NVARCHAR (8)    NULL,
    [CodigoPostal]                        INT             NULL,
    [FecPrimMatriculacion]                DATETIME        NULL,
    [IndNuevoUsado]                       NVARCHAR (1)    NULL,
    [PersonaFisicaJuridica]               NVARCHAR (1)    NULL,
    [CodigoItv]                           NVARCHAR (9)    NULL,
    [Servicio]                            NVARCHAR (3)    NULL,
    [CodMunicipioIneVeh]                  INT             NULL,
    [Municipio]                           NVARCHAR (30)   NULL,
    [KwItv]                               DECIMAL (18, 2) NULL,
    [NumPlazasMax]                        INT             NULL,
    [Co2Itv]                              INT             NULL,
    [Renting]                             NVARCHAR (1)    NULL,
    [CodTutela]                           NVARCHAR (1)    NULL,
    [CodPosesion]                         NVARCHAR (1)    NULL,
    [IndBajaDef]                          NVARCHAR (1)    NULL,
    [IndBajaTemp]                         NVARCHAR (1)    NULL,
    [IndSustraccion]                      NVARCHAR (1)    NULL,
    [BajaTelematica]                      NVARCHAR (11)   NULL,
    [TipoItv]                             NVARCHAR (25)   NULL,
    [VarianteItv]                         NVARCHAR (25)   NULL,
    [VersionItv]                          NVARCHAR (35)   NULL,
    [FabricanteItv]                       NVARCHAR (70)   NULL,
    [MasaOrdenMarchaItv]                  INT             NULL,
    [MasaMáximaTecnicaAdmisibleItv]       INT             NULL,
    [CategoríaHomologaciónEuropeaItv]     NVARCHAR (4)    NULL,
    [Carroceria]                          NVARCHAR (4)    NULL,
    [PlazasPie]                           INT             NULL,
    [NivelEmisionesEuroItv]               NVARCHAR (8)    NULL,
    [ConsumowhKmItv]                      NVARCHAR (4)    NULL,
    [ClasificaciónReglamentoVehiculosItv] NVARCHAR (4)    NULL,
    [CategoríaVehículoEléctrico]          NVARCHAR (4)    NULL,
    [AutonomíaVehículoEléctrico]          NVARCHAR (6)    NULL,
    [MarcaVehículoBase]                   NVARCHAR (30)   NULL,
    [FabricanteVehículoBase]              NVARCHAR (50)   NULL,
    [TipoVehículoBase]                    NVARCHAR (35)   NULL,
    [VarianteVehículoBase]                NVARCHAR (25)   NULL,
    [VersiónVehículoBase]                 NVARCHAR (35)   NULL,
    [DistanciaEjes12Itv]                  NVARCHAR (4)    NULL,
    [ViaAnteriorItv]                      NVARCHAR (4)    NULL,
    [ViaPosteriorItv]                     NVARCHAR (4)    NULL,
    [TipoAlimentacionItv]                 NVARCHAR (1)    NULL,
    [ContraseñaHomologacionItv]           NVARCHAR (25)   NULL,
    [EcoInnovacionItv]                    NVARCHAR (1)    NULL,
    [ReduccionEcoItv]                     NVARCHAR (4)    NULL,
    [CodigoEcoItv]                        NVARCHAR (25)   NULL,
    [FecProceso]                          DATETIME        NULL,
    CONSTRAINT [PK_dbo.VehicleData] PRIMARY KEY CLUSTERED ([Id] ASC)
);

