create view [vRegistro] as

SELECT  v.[Id]
      ,[TipoFichero]
      ,[NombreFichero]
      ,[FecMatricula]
      ,m.Descripcion as 'ClaseMat'
      ,[FecTramitacion]
      ,[MarcaItv]
      ,[ModeloItv]
      ,p.Descripcion as 'CodProcedenciaItv'
      ,[BastidorItv]
      ,[CodTipo]
      ,[CodPropulsionItv]
      ,[CilindradaItv]
      ,[PotenciaItv]
      ,[Tara]
      ,[PesoMax]
      ,[NumPlazasItv]
      ,[IndPrecinto]
      ,[IndEmbargo]
      ,[NumTransmisiones]
      ,[NumTitulares]
      ,[LocalidadVehiculo]
      ,[CodProvinciaVeh]
      ,[CodProvinciaMat]
      ,[ClaveTramite]
      ,[FecTramite]
      ,[CodigoPostal]
      ,[FecPrimMatriculacion]
      ,[IndNuevoUsado]
      ,[PersonaFisicaJuridica]
      ,[CodigoItv]
      ,[Servicio]
      ,[CodMunicipioIneVeh]
      ,[Municipio]
      ,[KwItv]
      ,[NumPlazasMax]
      ,[Co2Itv]
      ,[Renting]
      ,[CodTutela]
      ,[CodPosesion]
      ,[IndBajaDef]
      ,[IndBajaTemp]
      ,[IndSustraccion]
      ,[BajaTelematica]
      ,[TipoItv]
      ,[VarianteItv]
      ,[VersionItv]
      ,[FabricanteItv]
      ,[MasaOrdenMarchaItv]
      ,[MasaMáximaTecnicaAdmisibleItv]
      ,[CategoríaHomologaciónEuropeaItv]
      ,[Carroceria]
      ,[PlazasPie]
      ,[NivelEmisionesEuroItv]
      ,[ConsumowhKmItv]
      ,[ClasificaciónReglamentoVehiculosItv]
      ,[CategoríaVehículoEléctrico]
      ,[AutonomíaVehículoEléctrico]
      ,[MarcaVehículoBase]
      ,[FabricanteVehículoBase]
      ,[TipoVehículoBase]
      ,[VarianteVehículoBase]
      ,[VersiónVehículoBase]
      ,[DistanciaEjes12Itv]
      ,[ViaAnteriorItv]
      ,[ViaPosteriorItv]
      ,[TipoAlimentacionItv]
      ,[ContraseñaHomologacionItv]
      ,[EcoInnovacionItv]
      ,[ReduccionEcoItv]
      ,[CodigoEcoItv]
      ,[FecProceso]
  FROM [dbo].[VehicleData] v
  left outer join [dbo].[ClaseMat] m on v.CodClaseMat = m.Id
  left outer join [dbo].[ProcedenciaItv] p on  v.CodProcedenciaItv = p.Id;