//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DgtWsProxy.dgt {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dgt.es/iest/microdatos/descargas", ConfigurationName="dgt.descargaArchivoMicrodatosPortType")]
    public interface descargaArchivoMicrodatosPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación descargaArchivoMicrodatos no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="descargaArchivoMicrodatos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DgtWsProxy.dgt.descargaArchivoMicrodatosResponse descargaArchivoMicrodatos(DgtWsProxy.dgt.descargaArchivoMicrodatosRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.dgt.es/iest/microdatos/descargas/schema")]
    public partial class Peticion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Filtro filtroField;
        
        private MultiParte multiParteField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Filtro filtro {
            get {
                return this.filtroField;
            }
            set {
                this.filtroField = value;
                this.RaisePropertyChanged("filtro");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public MultiParte multiParte {
            get {
                return this.multiParteField;
            }
            set {
                this.multiParteField = value;
                this.RaisePropertyChanged("multiParte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dgt.es/iest/microdatos/descargas/schema")]
    public partial class Filtro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string categoriaField;
        
        private string subcategoriaField;
        
        private string fechaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("Categoria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Subcategoria {
            get {
                return this.subcategoriaField;
            }
            set {
                this.subcategoriaField = value;
                this.RaisePropertyChanged("Subcategoria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dgt.es/iest/microdatos/descargas/schema")]
    public partial class Estado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoEstadoField;
        
        private string literalErrorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("codigoEstado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string literalError {
            get {
                return this.literalErrorField;
            }
            set {
                this.literalErrorField = value;
                this.RaisePropertyChanged("literalError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dgt.es/iest/microdatos/descargas/schema")]
    public partial class IdentificadorRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idRespuestaField;
        
        private Filtro filtroField;
        
        private MultiParte multiParteField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idRespuesta {
            get {
                return this.idRespuestaField;
            }
            set {
                this.idRespuestaField = value;
                this.RaisePropertyChanged("idRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Filtro filtro {
            get {
                return this.filtroField;
            }
            set {
                this.filtroField = value;
                this.RaisePropertyChanged("filtro");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public MultiParte multiParte {
            get {
                return this.multiParteField;
            }
            set {
                this.multiParteField = value;
                this.RaisePropertyChanged("multiParte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dgt.es/iest/microdatos/descargas/schema")]
    public partial class MultiParte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreFicheroField;
        
        private string fragmentoField;
        
        private string numTotalFragmentosField;
        
        private string tamanoFicheroField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NombreFichero {
            get {
                return this.nombreFicheroField;
            }
            set {
                this.nombreFicheroField = value;
                this.RaisePropertyChanged("NombreFichero");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Fragmento {
            get {
                return this.fragmentoField;
            }
            set {
                this.fragmentoField = value;
                this.RaisePropertyChanged("Fragmento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumTotalFragmentos {
            get {
                return this.numTotalFragmentosField;
            }
            set {
                this.numTotalFragmentosField = value;
                this.RaisePropertyChanged("NumTotalFragmentos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TamanoFichero {
            get {
                return this.tamanoFicheroField;
            }
            set {
                this.tamanoFicheroField = value;
                this.RaisePropertyChanged("TamanoFichero");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.dgt.es/iest/microdatos/descargas/schema")]
    public partial class Respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdentificadorRespuesta identificadorRespuestaField;
        
        private Estado estadoField;
        
        private string datosSalidaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public IdentificadorRespuesta identificadorRespuesta {
            get {
                return this.identificadorRespuestaField;
            }
            set {
                this.identificadorRespuestaField = value;
                this.RaisePropertyChanged("identificadorRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Estado estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string datosSalida {
            get {
                return this.datosSalidaField;
            }
            set {
                this.datosSalidaField = value;
                this.RaisePropertyChanged("datosSalida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargaArchivoMicrodatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dgt.es/iest/microdatos/descargas/schema", Order=0)]
        public DgtWsProxy.dgt.Peticion Peticion;
        
        public descargaArchivoMicrodatosRequest() {
        }
        
        public descargaArchivoMicrodatosRequest(DgtWsProxy.dgt.Peticion Peticion) {
            this.Peticion = Peticion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargaArchivoMicrodatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dgt.es/iest/microdatos/descargas/schema", Order=0)]
        public DgtWsProxy.dgt.Respuesta Respuesta;
        
        public descargaArchivoMicrodatosResponse() {
        }
        
        public descargaArchivoMicrodatosResponse(DgtWsProxy.dgt.Respuesta Respuesta) {
            this.Respuesta = Respuesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface descargaArchivoMicrodatosPortTypeChannel : DgtWsProxy.dgt.descargaArchivoMicrodatosPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class descargaArchivoMicrodatosPortTypeClient : System.ServiceModel.ClientBase<DgtWsProxy.dgt.descargaArchivoMicrodatosPortType>, DgtWsProxy.dgt.descargaArchivoMicrodatosPortType {
        
        public descargaArchivoMicrodatosPortTypeClient() {
        }
        
        public descargaArchivoMicrodatosPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public descargaArchivoMicrodatosPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public descargaArchivoMicrodatosPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public descargaArchivoMicrodatosPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DgtWsProxy.dgt.descargaArchivoMicrodatosResponse DgtWsProxy.dgt.descargaArchivoMicrodatosPortType.descargaArchivoMicrodatos(DgtWsProxy.dgt.descargaArchivoMicrodatosRequest request) {
            return base.Channel.descargaArchivoMicrodatos(request);
        }
        
        public DgtWsProxy.dgt.Respuesta descargaArchivoMicrodatos(DgtWsProxy.dgt.Peticion Peticion) {
            DgtWsProxy.dgt.descargaArchivoMicrodatosRequest inValue = new DgtWsProxy.dgt.descargaArchivoMicrodatosRequest();
            inValue.Peticion = Peticion;
            DgtWsProxy.dgt.descargaArchivoMicrodatosResponse retVal = ((DgtWsProxy.dgt.descargaArchivoMicrodatosPortType)(this)).descargaArchivoMicrodatos(inValue);
            return retVal.Respuesta;
        }
    }
}
